import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import React, {useState } from 'react'
import Axios from 'axios'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
    const [logUser, setUser] = useState('')
    const [logPass, setPass] = useState('')
    const [logStatuseErr, setLogstaterr] = useState('')
    const login = () =>{
        Axios.post('http://localhost:2023/read',{
          username: logUser, 
          password: logPass
        }).then((response) => {
          if (response.data.message){
            setLogstaterr(response.data.message)
          }else{
            setLogstaterr('An Error Occured')
          }
          console.log(response);
        });

    };
  return (
    <>
      <Head>
        <title>Motion Detection - Login</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossOrigin="anonymous"></link>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossOrigin="anonymous"></script>
        <script src="//cdn.jsdelivr.net/npm/sweetalert2@11"></script>
      </Head>

      <section className="vh-100 gradient-custom">
          <div className="container py-5 h-100">
            <div className="row d-flex justify-content-center align-items-center h-100">
              <div className="col-12 col-md-8 col-lg-6 col-xl-5">
                <div className="card bg-dark text-white">
                  <div className="card-body p-5 text-center">

                    <div className="mb-md-5 mt-md-4 pb-5">

                      <h2 className="fw-bold mb-2 text-uppercase">Login</h2>
                      <p className="text-white-50 mb-5">Please enter your username and password   </p>

                      <form action="">
                        <h3 className='text-danger'>{logStatuseErr}</h3>
                        <div className="form-outline form-white mb-4">
                          <input type="text" id="typeUsernameX" onChange={(e)=>{setUser(e.target.value);}} className="form-control form-control-lg" placeholder='Enter Username' required />
                        </div>

                        <div className="form-outline form-white mb-4">
                          <input type="password" id="typePasswordX" onChange={(e)=>{setPass(e.target.value);}} className="form-control form-control-lg" placeholder='Enter Password' required />
                        </div>

                        <p className="small mb-5 pb-lg-2"><a className="text-white-50" data-bs-toggle="modal" data-bs-target="#forgotpass" href="">Forgot password?</a></p>

                        <button className="btn btn-outline-light btn-lg px-5" onClick={login} type="submit">Login</button>
                      </form>

                    </div>

                    <div>
                      <p className="mb-0">Don't have an account? <a href="signup" className="text-white-50 fw-bold">Sign Up</a>
                      </p>
                    </div>

                  </div>
                </div>
              </div>
            </div>
          </div>
        </section>

        <div className="modal fade" id="forgotpass" aria-labelledby="exampleModalLabel" aria-hidden="true">
          <div className="modal-dialog">
            <div className="modal-content">
              <div className="modal-header">
                <h5 className="modal-title text-dark " id="exampleModalLabel">Forgot Password</h5>
                <button type="button" className="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
              </div>
              <form>
                <div className="modal-body">
  
                  <input type="email" id="typeEmailX" className="form-control form-control-lg" placeholder='Enter Email' required />
                
                </div>
                <div className="modal-footer">
                  <button type="button" className="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                  <button type="submit" className="btn btn-danger">Submit</button>
                </div>
              </form>

            </div>
          </div>
        </div>
    </>
  )
}