import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import React, {useState } from 'react'
import Axios from 'axios' 
import Link from 'next/link'
import Script from 'next/script'
// import {signIn, signOut, useSession} from 'next-auth/react'
// import { SessionProvider } from "next-auth/react"

const inter = Inter({ subsets: ['latin'] })
export const getStaticProps = async() =>{
    const res = await fetch('http://localhost:2023/data');
    const data = await res.json();

    return  {
        props: {image_blob: data}
    }
}
const getData = ({ image_blob }) =>{
    
  return (
    <>
      <Head>
        <title>Motion Detection - Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossOrigin="anonymous"></link>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossOrigin="anonymous"></script>
        <script src="//cdn.jsdelivr.net/npm/sweetalert2@11"></script>
        <script src="main_script.js"></script>
      </Head>
    
        <nav className="navbar navbar-expand-lg bg-secondary text-uppercase fixed-top" id="mainNav">
            <div className="container">
                <a className="navbar-brand" href="#">Motion Detection</a>
                <button className="navbar-toggler text-uppercase font-weight-bold bg-primary text-white rounded" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                    Menu
                    <i className="fas fa-bars"></i>
                </button>
                <div className="collapse navbar-collapse" id="navbarResponsive">
                    <ul className="navbar-nav ms-auto">
                        <li className="nav-item mx-0 mx-lg-1"><a className="nav-link py-3 px-0 px-lg-3 rounded" href="#team">Team</a></li>
                        <li className="nav-item mx-0 mx-lg-1"><a className="nav-link py-3 px-0 px-lg-3 rounded" href="./">Logout</a></li>
                    </ul>
                </div>
            </div>
        </nav>

        <header className="masthead bg-primary text-white text-center">
            <div className="container d-flex align-items-center flex-column">
                <img className="masthead-avatar mb-2" src="./motion.gif" alt="..." />
                <h1 className="masthead-heading text-uppercase mb-5">Motion Detection</h1>
                <p className="masthead-subheading font-weight-light mb-5">Simply open a camera you can now detect motion <br/> and you can view all the detected motion in images.</p>
            </div>
        </header>


        <section className="page-section portfolio" id="portfolio">
            <div className="container">
        
                <h2 className="page-section-heading text-center text-uppercase text-secondary">List of Detected motions</h2>
                <div className="divider-custom mb-5">
                    <div className="divider-custom-line"></div>
                    <div className="divider-custom-icon"><i className="fas fa-star"></i></div>
                    <div className="divider-custom-line"></div>
                </div>

                <div className="row justify-content-center">

                    <table class="table table-bordered table-hover">
                        <thead>
                            <tr>
                                <th scope="col">Date and Time</th>
                                <th scope="col">Captured Image</th>

                            </tr>
                        </thead>
                        <tbody>
                        {image_blob.map(datas => (
                        <tr>
                            <td>{datas.date_time}</td>
                            <td className='text-center'>
                            <img className='im' width="250" src={`data:image/png;base64,${datas.image}`}
                            /></td>      
                        </tr>
                        ))} 
                        </tbody>
                    </table>

                </div>
            </div>
        </section>
    
        <section className="page-section bg-dark text-white mb-0" id="team">
            <div className="container">
           
                <h2 className="page-section-heading text-center text-uppercase text-white">Meet our Team</h2>
            
                <div className="divider-custom divider-light mb-5">
                    <div className="divider-custom-line"></div>
                    <div className="divider-custom-icon"><i className="fas fa-star"></i></div>
                    <div className="divider-custom-line"></div>
                </div>
            
                <div className="row mb-5">
                    <div className="col-lg-4 text-center"> 
                        <img className="img-fluid mb-3" src="./team/mel.jpg" width="300" alt="..." />
                        <h4 className="text-center">Melisa Manalili</h4>
                    </div>
                    <div className="col-lg-4 text-center"> 
                        <img className="img-fluid mb-3" src="./team/rai.jpg" width="300" alt="..." />
                        <h4 className="text-center">Raiza Gumarang</h4>
                    </div>
                    <div className="col-lg-4 text-center"> 
                        <img className="img-fluid mb-3" src="./team/seya.jpg" width="300" alt="..." />
                        <h4 className="text-center">Kazzeah Permejo</h4>
                    </div>
                </div>

                <div className="row justify-content-center">
                    <div className="col-lg-4 text-center"> 
                        <img className="img-fluid mb-3" src="./team/seph.jpg" width="300" alt="..." />
                        <h4 className="text-center">Joseph Azupardo</h4>
                    </div>
                    <div className="col-lg-4 text-center"> 
                        <img className="img-fluid mb-3" src="./team/aj.jpg" width="285" alt="..." />
                        <h4 className="text-center">Avor John Narag</h4>
                    </div>
                   
                </div>
       
            </div>
        </section>
 
        <footer className="footer text-center">
            <div className="container">
                <div className="text-center text-white p-3">
                    © 2023 All Rights Reserved:   <a href='#'>Motion Detection</a>
                </div>
            </div>
        </footer>

    </>
  )
}


export const config = {
    api: {bodyParser: {
            sizeLimit: '4mb',
        },
    },
}
export default getData;