import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import React, {useState } from 'react'
import Axios from 'axios' 
// import styles from '../styles/custom.module.css'
import Script from 'next/script'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Motion Detection - Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous"></link>
        <Script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"/>
        <Script src="//cdn.jsdelivr.net/npm/sweetalert2@11"/>
        <Script src="main_script.js"/>
      </Head>
    
        <nav class="navbar navbar-expand-lg bg-secondary text-uppercase fixed-top" id="mainNav">
            <div class="container">
                <a class="navbar-brand" href="#">Motion Detection</a>
                <button class="navbar-toggler text-uppercase font-weight-bold bg-primary text-white rounded" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                    Menu
                    <i class="fas fa-bars"></i>
                </button>
                <div class="collapse navbar-collapse" id="navbarResponsive">
                    <ul class="navbar-nav ms-auto">
                        <li class="nav-item mx-0 mx-lg-1"><a class="nav-link py-3 px-0 px-lg-3 rounded" href="#team">Team</a></li>
                        <li class="nav-item mx-0 mx-lg-1"><a class="nav-link py-3 px-0 px-lg-3 rounded" href="#contact">Logout</a></li>
                    </ul>
                </div>
            </div>
        </nav>

        <header class="masthead bg-primary text-white text-center">
            <div class="container d-flex align-items-center flex-column">
                <img class="masthead-avatar mb-2" src="./motion.gif" alt="..." />
                <h1 class="masthead-heading text-uppercase mb-5">Motion Detection</h1>
                <p class="masthead-subheading font-weight-light mb-5">Simply open a camera you can now detect motion <br/> and you can view all the detected motion in images.</p>
                <button class="btn btn-success">OPEN CAMERA</button>
            </div>
        </header>


        <section class="page-section portfolio" id="portfolio">
            <div class="container">
        
                <h2 class="page-section-heading text-center text-uppercase text-secondary">List of Detected motions</h2>
                <div class="divider-custom mb-5">
                    <div class="divider-custom-line"></div>
                    <div class="divider-custom-icon"><i class="fas fa-star"></i></div>
                    <div class="divider-custom-line"></div>
                </div>
         
                <div class="row justify-content-center">
                
                    <div class="col-md-6 col-lg-4 mb-5">
                        <div class="portfolio-item mx-auto">
                            <img class="img-fluid" src="./sample1.jpg" alt="..." />
                        </div>
                    </div>
                    <div class="col-md-6 col-lg-4 mb-5">
                        <div class="portfolio-item mx-auto">
                            <img class="img-fluid" src="./sample2.jpg" alt="..." />
                        </div>
                    </div>

                </div>
            </div>
        </section>


        <section class="page-section bg-dark text-white mb-0" id="team">
            <div class="container">
           
                <h2 class="page-section-heading text-center text-uppercase text-white">Meet our Team</h2>
            
                <div class="divider-custom divider-light mb-5">
                    <div class="divider-custom-line"></div>
                    <div class="divider-custom-icon"><i class="fas fa-star"></i></div>
                    <div class="divider-custom-line"></div>
                </div>
            
                <div class="row mb-5">
                    <div class="col-lg-4 text-center"> 
                        <img class="img-fluid mb-3" src="./team/mel.jpg" width="300" alt="..." />
                        <h4 class="text-center">Melisa Manalili</h4>
                    </div>
                    <div class="col-lg-4 text-center"> 
                        <img class="img-fluid mb-3" src="./team/rai.jpg" width="300" alt="..." />
                        <h4 class="text-center">Raiza Gumarang</h4>
                    </div>
                    <div class="col-lg-4 text-center"> 
                        <img class="img-fluid mb-3" src="./team/seya.jpg" width="300" alt="..." />
                        <h4 class="text-center">Kazzeah Permejo</h4>
                    </div>
                </div>

                <div class="row justify-content-center">
                    <div class="col-lg-4 text-center"> 
                        <img class="img-fluid mb-3" src="./team/seph.jpg" width="300" alt="..." />
                        <h4 class="text-center">Joseph Azupardo</h4>
                    </div>
                    <div class="col-lg-4 text-center"> 
                        <img class="img-fluid mb-3" src="./team/aj.jpg" width="285" alt="..." />
                        <h4 class="text-center">Avor John Narag</h4>
                    </div>
                   
                </div>
       
            </div>
        </section>
 
        <footer class="footer text-center">
            <div class="container">
                <div class="text-center text-white p-3">
                    © 2023 All Rights Reserved:   <a href='#'>Motion Detection</a>
                </div>
            </div>
        </footer>

    </>
  )
}
